// Code generated by protoc-gen-go from "header.proto"
// DO NOT EDIT!

package protorpc

import proto "goprotobuf.googlecode.com/hg/proto"

// Reference proto import to suppress error if it's not otherwise used.
var _ = proto.GetString

type Header struct {
	Seq	*uint64	"PB(varint,1,req,name=seq)"
	ServiceMethod	*string	"PB(bytes,2,req,name=service_method)"
	Error	*string	"PB(bytes,3,opt,name=error)"
	XXX_unrecognized	[]byte
}
func (this *Header) Reset() {
	*this = Header{}
}
func NewHeader() *Header {
	return new(Header)
}

func init() {
}
