# Copyright 2010 Eric Clark. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=protoc-gen-protorpc-go

GOFILES=\
    $(GOROOT)/src/pkg/goprotobuf.googlecode.com/hg/compiler/main.go\
    rpcplugin.go\

include $(GOROOT)/src/Make.cmd

